# Generated by Django 5.0.7 on 2024-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='default title'),
        ),
    ]
