# Generated by Django 5.0.7 on 2024-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('main_cast', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('running_time', models.IntegerField()),
                ('review_text', models.TextField()),
            ],
        ),
    ]
